### ISSUE TITLE
Hey, i have problem can you help me ?

### ISSUE THREAD

**Issue by muratcansimsek** [GrimReaperFloof/STARK#1] opened 2019-11-30 12:28 UTC
I can't see Cable Output on Standart Output settings.

I already installed VB-CABLE. 

What is wrong? 

If you have time, can you help me with TeamViewer? 

My discord : 🌈Murat Can Şimşek💖#6666

![pb1](https://user-images.githubusercontent.com/25007736/69900562-0cd43280-1386-11ea-88ce-a8b957312ff7.png)
![prb](https://user-images.githubusercontent.com/25007736/69900563-0cd43280-1386-11ea-84e9-d34ebfd13d57.png)

**Comment by muratcansimsek** [comment] 2019-11-30 12:51
![line](https://user-images.githubusercontent.com/25007736/69900795-275bdb00-1389-11ea-9ff1-a175ba1a0697.png)
finally i change to line 1 

when i open csgo and try to say .tts hello not working what is wrong? i try everything

**Comment by fuck-shithub** [comment] 2019-12-01 10:57
When you have STARK running, you need to open the game developer console and execute the command
```
exec stark
```
You have to do this every time you restart your game.
If the command doesn't work that's usually because STARK is not running. Make sure STARK is running before you execute the command.

**Comment by muratcansimsek** [comment] 2019-12-01 17:49
I know how to run for csgo, im SLAM user.

But when i open csgo chat and say .tts hello nothing happens

**Comment by fuck-shithub** [comment] 2019-12-01 22:42
Have you opened `game.txt` and set the game to `csgo`? If not, then do that.
Then restart STARK and try executing `exec stark` in your game console again.

**Comment by muratcansimsek** [comment] 2019-12-02 07:34
i already did it.

I think there's another problem

**Comment by fuck-shithub** [comment] 2019-12-02 14:26
Your audio settings seem correct, but just to make sure, go to the Synthesizer tab and manually type in a TTS message there. Tell me if you can hear it when you do that.

**Comment by muratcansimsek** [comment] 2019-12-02 19:45
Yeah i already did, literally working on Synthesizer tab.

But not working on csgo.

**Comment by fuck-shithub** [comment] 2019-12-02 22:35
Weird. Does `exec stark` give an error? Or does it output a list of commands that you can use (not all commands are listed btw because I fucked up)

**Comment by muratcansimsek** [comment] 2019-12-03 13:21
When I write exec stark, I see a list of commands that can be implemented on the console. (csgo)

But it doesn't work when I try the commands.

**Comment by muratcansimsek** [comment] 2019-12-06 06:09
still not working

**Comment by fuck-shithub** [comment] 2019-12-06 17:36
I've tested myself, and for some reason, CS:GO doesn't want to output console output to the text file STARK uses to read chat. I don't know what Valve has done but I suppose it's broken now, and I don't know if there is any way to fix this. Team Fortress 2 still works though.

**Comment by axynos** [comment] 2019-12-30 20:16
Heya, it's been a while!

It seemed weird that the devs would remove a command so necessary, so tested it a bit myself. 

The command still works, just a bit differently. It seems like they silently added the requirement for the file to include a `.log` file extension. The new filename format is `yourfilename.log` I've forgotten where the con_logfile output put the file when I first developed it, but it's in the `csgo` folder in my testing.

See the [attached (zipped) video](https://github.com/GrimReaperFloof/STARK/files/4010893/con_logfile.zip)  for a demonstration.

Keep it alive, peeps! 💛

**Comment by axynos** [comment] 2019-12-31 18:39
@GrimReaperFloof I suggest closing the issue now, as the problem is fixed with the latest merge.

**Comment by fuck-shithub** [comment] 2019-12-31 21:30
The problem is fixed, but I haven't yet compiled it into an executable yet. Playing YouTube videos is broken and I'm looking if I can fix it as well.

**Comment by fuck-shithub** [comment] 2020-01-02 22:56
Alright, I've released a new version of STARK now. This one should work with CS:GO.
https://github.com/GrimReaperFloof/STARK/releases

**Closed as completed** 2020-01-03 12:47 UTC
